### ISSUE TITLE
Support for AFP 3.4

### ISSUE THREAD

**Issue by rdmark** [Netatalk/afptest#3]
# AFP 3.4

> Introduced in OS X v10.8. Changes the error code mapping so that the POSIX error code ENOATTR maps onto the kFPItemNotFound AFP error code. (In previous versions, an ENOATTR on the server side produced a kFPMiscErr AFP error code.)

https://developer.apple.com/library/archive/documentation/Networking/Conceptual/AFP/AFPVersionDifferences/AFPVersionDifferences.html#//apple_ref/doc/uid/TP40000854-CH230-SW12

**Comment by NJRoadfan** [comment]
I haven't found an archived version of the AFP3.4 spec yet, but here is AFP3.3: https://web.archive.org/web/20110614181355/http://developer.apple.com/library/mac/#documentation/Networking/Reference/AFP_Reference/Reference/reference.html#//apple_ref/doc/uid/TP40003548

**Comment by rdmark** [comment]
I added surface level support for AFP 3.4 with https://github.com/Netatalk/afptest/commit/d1317bb0d302f545d039e330853b9b4b6c9379ac -- now you can at least tell the server that you support this protocol version. The difference with 3.3 is very minute anyways.
